<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>audiencemenuicon</name>
   <tag></tag>
   <elementGuidId>b0342ed2-bfe1-467b-b20c-3583b9ee5c44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='init']/div/div[2]/div/nav/div/ul/li[1]/a/div/*[name()='svg']/*[name()='path']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
